freedomjs/freedom

package.json, spec/providers/coreIntegration/udpsocket.integration.src.js
The test now passes on both Firefox and Chrome.
This resolves https://github.com/freedomjs/freedom/issues/155
=> Fix UDP integration test.

spec/src/provider.spec.js, src/provider.js
=> Reject improper provider behavior

spec/providers/coreIntegration/rtcpeerconnection.integration.src.js
Fixes 1 of the 3 failing tests covered by https://github.com/freedomjs/freedom-for-firefox/issues/29
=> Add timeout in sending message rtc offer creation to make firefox happy

demo/customchannel/index.html, demo/customchannel/main.js, src/module.js
Addresses #231  as can be seen in the updated demo.
=> make sure closing due to errors is a bit more forceful.

karma.conf.js, spec/providers/social/social.double.integration.src.js
Handles cases when events arrive in different orders.
=> Social integration tests: flaky no more!

providers/core/core.rtcdatachannel.js, spec/providers/coreIntegration/rtcpeerconnection.integration.src.js
This resolves https://github.com/freedomjs/freedom/issues/251
=> Ensure that the datachannel provider doesn't lose early events.

src/module.js, src/provider.js
improve some warnings to make development a bit easier.
=> Improve warnings

spec/providers/coreIntegration/tcpsocket.integration.src.js
Cleanups and tweaks that facilitate these tests passing in Firefox.
=> Soycode fftesttweaks

spec/providers/coreIntegration/tcpsocket.integration.src.js
To prevent this issue from creeping in again:
https://github.com/freedomjs/freedom-for-firefox/issues/72
=> test that onConnection sockets dispatch onDisconnect

spec/providers/coreIntegration/tcpsocket.integration.src.js
Fix https://github.com/freedomjs/freedom-for-chrome/issues/82
=> tcp onDisconnect test pass in chrome

spec/providers/coreIntegration/oauth.integration.src.js
Stopgap for #292, real fix still needed.
=> disabling broken oauth test

spec/providers/coreIntegration/tcpsocket.integration.src.js
At least partially addresses https://github.com/freedomjs/freedom-for-node/issues/37.
=> Soycode tcptesttweaks

interface/core.udpsocket.json
Fix #283 
See also:
- https://github.com/freedomjs/freedom-for-firefox/pull/85
- https://github.com/freedomjs/freedom-for-chrome/pull/85
=> udp errcode add already_closed, fix typo

Gruntfile.js, package.json
Small tweaks to smooth over current CI issues.
=> Soycode saucelabs

.gitignore, spec/helper/broken.json
=> Add missing manifest for the broken module.  Oops.

spec/providers/coreIntegration/tcpsocket.integration.src.js, src/util.js
Inelegant but functional and perhaps necessary tweaks to get tests to pass.
=> Fix integration tests in Chrome and Firefox

.shippable.yml, .travis.yml, Gruntfile.js, package.json
Fix https://github.com/freedomjs/freedom/issues/287
=> Soycode removegruntreplace

providers/core/core.rtcpeerconnection.js, spec/providers/coreIntegration/rtcpeerconnection.integration.src.js
Companion pull request for https://github.com/freedomjs/freedom-for-node/pull/40
Test and implementation tweaks so core.rtcpeerconnection works in node.
=> Soycode nodewrtc

interface/core.battery.json, providers/core/core.battery.js, spec/providers/core/core.battery.spec.js, src/util/workerEntry.js
See https://developer.mozilla.org/en-US/docs/Web/API/Navigator/getBattery
=> Add a core provider to expose the BatteryManager API

spec/providers/coreIntegration/tcpsocket.integration.src.js
New test for issue from https://github.com/freedomjs/freedom-for-chrome/issues/90 (sockets raising error when closing in Chrome)
=> Soycode newtcptest
