freedomjs/freedom

spec/providers/coreIntegration/udpsocket.integration.src.js
I'm not sure how I missed this when testing https://github.com/freedomjs/freedom/pull/182 ... oh well.
=> Make the UDP socket integration test pass in freedom-for-firefox

providers/core/core.xhr.js, spec/providers/coreIntegration/xhr.integration.src.js
Some small changes to allow us to reuse most of this code for freedom-for-node.
Allows specifying an alternative XMLHttpRequest and take out a couple tests for things that haven't yet been implemented in the "xhr2" npm module yet.
=> core.xhr compatibility with freedom-for-node

Gruntfile.js, package.json, tasks/publishWebsite.js, tasks/report-stats.js
Resolve #161
This saves to a spreadsheet that we can then build graphs off of. Tracks file size of freedom.js (non-minimized) & build time on travis.
=> Track bundle size.

interface/core.tcpsocket.json
This is driven by SOCKS server implementation, which should
report more detailed information to the client when a
connection fails.
See https://github.com/uProxy/uproxy/issues/800
=> Add some more error codes to the core.tcpsocket interface.

.gitignore, Gruntfile.js, karma.conf.js, spec/providers/provider.integration.spec.js, spec/providers/social/social.double.integration.src.js, spec/providers/social/social.single.integration.src.js, spec/providers/storage/storage.integration.src.js
Refactored social and storage integration tests to be independent CommonJS modules that can be easily used in other repositories. No longer requires testUtils or other internal files.
Notes
- transport tests have not been refactored yet due to lack of support for custom channels in the outer page context.
- We should probably clean up root freedom modules that are created, but I couldn't find examples or documentation where we do that.
=> refactoring social/storage integration tests

spec/providers/coreIntegration/tcpsocket.integration.src.js
A better approach - it turns out that, for grunt-jasmine-node2 at least, the three socket-using tests end up clobbering each other (connection reset error) as they were formulated. I cleaned up the "Works as a Client" test a bit as was discussed, but that wasn't the core issue - I think it had more to do with the done() being invoked before the various close() calls in "Sends from Client to Server".
In any case, this passes now, let me know thoughts - thanks!
=> fix tcp integration to avoid tests clobbering each others connections

interface/core.tcpsocket.json, spec/providers/coreIntegration/tcpsocket.integration.src.js
Meant to fix #128 and currently passes in freedom-for-chrome. Doesn't completely pass in freedom-for-firefox (but neither do the integration tests in general), and the jasmine_node task is more generally failing for me right now in freedom-for-node. Besides investigating that, main todos:
- Clarify whether some calls really should give an error or not (e.g. getInfo on a closed socket)
- Consider making error messages consistent across providers (e.g. 'NOT_CONNECTED' in Chrome versus 'SOCKET_NOT_CONNECTED' in Firefox) - if these differences reflect actual underlying differences in the browsers themselves then maybe keep them
- Implement the remaining tests, in particular more tests around using 'secure' (which only seems to be implemented in Chrome, so the test may need some conditionality …
=> Soycode tcpintegration

.shippable.yml
This is meant to address this warning I saw on Shippable:
#@                                                           @#
#@  You can create an x11vnc password file by running:       @#
#@                                                           @#
#@       x11vnc -storepasswd password /path/to/passfile      @#
#@  or   x11vnc -storepasswd /path/to/passfile               @#
#@  or   x11vnc -storepasswd                                 @#
#@                                                           @#
#@  (the last one will use ~/.vnc/passwd)                    @#
#@                                                           @#
#@  and then starting x11vnc via:                            @#
#@                                                           @#
#@      x11vnc -rfbauth …
=> nopw option to disable vnc warning on shippable

interface/core.crypto.json, providers/core/core.crypto.js, spec/providers/core/core.crypto.unit.spec.js
```javascript
freedom['core.crypto']().getRandomBytes(n).then(function (buffer) {
...
});
```
address https://github.com/freedomjs/freedom-for-firefox/issues/33
=> expose core randomness

spec/providers/coreIntegration/xhr.integration.src.js
I believe the recent test issues had to do with this Mozilla bug that they addressed in Firefox 37: https://bugzilla.mozilla.org/show_bug.cgi?id=707484
"The latest XHR2 spec allows setting responseType and withCredentials in UNSENT or OPENED state." - it seems to me that this means that getReadyState can return a 0 or a 1, potentially. I'm not sure that this is truly the correct interpretation, but empirically it's what is happening, hence this diff. LMK thoughts - thanks!
=> xhr integration compatible w/xhr2 state flexibility

providers/core/core.console.js
Two main changes:
1. reset the text colour after printing the module name
1. make the Firefox JSM log format more like we get in the browser, viz. `module X message`, where `module` is the module name, `X` indicates the level, and `message` is the message.
AFAICT, only the Firefox JSM environment needs special-casing: I tested this on Chrome and Firefox web and add-on environments, plus Firefox's Browser Console.
=> fix core.console source field formatting and simplify

package.json
(Hack) Fix #276 
The real fix is for the various dependencies to deal properly with unicode, as documented in the issue. I briefly toyed with changing our build process to temporarily remove comments etc. etc. but decided this was a more parsimonious approach for the time being.
=> temporarily pin grunt-browserify version to fix sourcemaps

bower.json, package.json
Noticed grunt-bump was pinned, looks like it doesn't have to be. No API changes that affect our specified options, the main new thing seems to be the ability to run `grunt bump --dry-run` to have it print what it will do without actually doing it (which is rather nice actually). While doing so I also noticed that the versions in package.json and bower.json are in disagreement, so fixing that here as well.
=> update grunt-bump, align versions

interface/core.oauth.json, package.json, providers/core/core.oauth.js, providers/oauth/oauth.localpageauth.js, providers/oauth/oauth.remotepageauth.js, spec/providers/core/oauth.unit.spec.js
This is part of a group of pull requests that add a new "interactive" param to the core.oauth launchAuthFlow API.  If this interactive param is false, Chrome + Firefox oauth tabs should open in the background (not be focused).  This results in a better reconnect UX for Facebook.
Related pull requests:
* https://github.com/uProxy/uproxy/pull/1698
* https://github.com/freedomjs/freedom-social-firebase/pull/29
* https://github.com/freedomjs/freedom-for-firefox/pull/70
* https://github.com/freedomjs/freedom-for-chrome/pull/78
=> Add interactive param to oauth provider

spec/providers/coreIntegration/oauth.integration.src.js
This new test case checks that if the interactive parameter to launchAuthFlow is false, and the user is not redirected to the expected redirect url, then launchAuthFlow fails.
For this test, I had to modify jasmine.DEFAULT_TIMEOUT_INTERVAL to be 6000 ms, instead of the default 3000 ms.  This is because for tab authentication in Firefox and Chrome, if 5000 ms passes with a successful redirect, we close the tab and reject the promise returned by launchAuthFlow.  I tried using the jasmine.clock().tick(5000) to invoke this timeout, but that was not working.  I even made a simple test case to check on the jasmine clock behavior which I think should pass but times out instead:
```
it("async test", function (done) {
jasmine.clock().install();
setTimeout(function() {
done();
}, 5000); …
```
=> Add new oauth integration test for interactive=false case

providers/oauth/oauth.localpageauth.js, providers/oauth/oauth.remotepageauth.js
Tested with "grunt test".  Some storage tests have been failing and continue to fail, but this makes the oauth tests all pass
=> Abort oauth flow after 5 seconds if interactive==false and no redirect

src/resource.js
This makes Freedom continue working with Cordova Chrome Apps 0.7.3.
=> Add support for gopher:// URLs.  Yeah.

spec/providers/coreIntegration/tcpsocket.integration.src.js
Note: This test fails in freedom-for-chrome, pending https://github.com/freedomjs/freedom-for-chrome/pull/86
=> Fix SSL integration test for TCP sockets

spec/providers/coreIntegration/tcpsocket.integration.src.js, spec/providers/storage/storage.integration.src.js
@ryscheng @willscott 
Not high priority, but I'm re-disabling this test - I had enabled it because it was passing in freedom(-for-firefox, -for-chrome), but I'm now revisiting freedom-for-node for the first time in awhile (https://github.com/freedomjs/freedom-for-node/tree/soycode-cleanup) and have found that this test does *not* pass in it.
That, combined with the good question raised by the TODO of whether this behavior is even desired, suggests I should disable the test. However if either of you think this test should be desired behavior (since it is what freedom does in most environments) then I can leave it enabled and focus on getting the node flavor to pass it.
=> disabling cross-instance storage test, node tcp pause/resume test

spec/helper/environment.js, spec/helper/environment.json, spec/providers/coreIntegration/environment.integration.src.js, src/link/frame.js, src/module.js, src/moduleinternal.js
Prior to this change, all dependencies specified in a module's
manifest were loaded and started before that module could start.
With this change, the main module is loaded immediately, and each
dependency is only loaded after its constructor is called.
This design makes startup faster, and reduces memory usage for
projects that contain optional modules.
This change does not alter any explicit API, but it does change
the semantics of modules that perform actions before their
constructor is called.  Any such actions will now be delayed until
after the first constructor call.  I am not aware of any such
modules currently in existence.
=> Lazy module loading

spec/providers/coreIntegration/rtcpeerconnection.integration.src.js
I'm not sure why the test was written the way it was, I rewrote to get at what I think it's testing for. It (still) passes in firefox/chrome (doesn't pass in node, which is why I was looking at this in the first place - but I think the fix is node-side).
=> clarify rtcpeer onClose test

package.json, src/resource.js
Fix #319 
Hopefully it's okay to make xhrRetriever synchronous, as that seems to be what Chrome wants.
=> make xhrRetriever resource loader synchronous (fix for Chrome change)

src/resource.js
Fix (most of) the tests failing in https://github.com/freedomjs/freedom-for-chrome/pull/89
=> switch back to async xhrRetriever *except* chrome non-app

providers/core/core.battery.js
This is a fix for environments without the navigator object (such as node), which can fail (trying to refer to undefined) with the prior logic.
=> explicitly check for defined navigator object in core.battery

providers/core/core.online.js
I was working on cutting new releases and found that core integration tests were failing because the environment was referring to undefined variables. This tweak fixes that, and then I'll cut a release here and in the firefox and chrome flavors.
For the flavors, I think the only thing to do is add the provider to entry (https://github.com/freedomjs/freedom-for-firefox/commit/129bab93e2b3089ee533e61cb057555fbfd5e1d7, https://github.com/freedomjs/freedom-for-chrome/commit/98aa7a230092bf21d7c2507fae7a3fac912a7442) and bump the freedom version dependency as appropriate, as this is a fairly simple provider. Let me know if I'm missing something though - thanks!
=> ensure nav/win are false if navigator/window undefined

npm-shrinkwrap.json
Fix #311 
Dependencies are fairly fresh, things that are held back are chosen on purpose (so that build/tests still work).
=> add npm shrinkwrap (freeze dependencies)
